name: Build Image

on: [push] # When pushing to any branch then run this action

# Env variable
env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_US }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PAS }}
  REPO_NAME: ${{ secrets.DOCKERHUB_REPO }}
  
jobs:
  push-docker-hub:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code
    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d_%M%S')"
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
  push:
    needs: push-docker-hub
    runs-on: ubuntu-latest
    steps:
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
